### ISSUE TITLE
add templates for issues and pull requests

### ISSUE THREAD

**Issue by danshaub** [Nebulaworks/orion#14]
## Description
Orion doesn't have built in templates for issues or pull requests. For consistency's sake, they could be the same as those in Infra:

### Issue:
>  ## Description
> Brief description of the issue
> 
> ## Acceptance Criteria
> Requirements needed to validate that this issue is complete

### PR:

> ## Description of PR
> Brief description of the PR
> 
> ## Previous Behavior
> Remove this section if not relevant
> 
> ## New Behavior
> Remove this section if not relevant
> 
> ## Tests
> How was this PR tested?

## Acceptance Criteria
New issues and pull requests are populated with a template.

**Comment by sarcasticadmin** [comment]
@danshaub great idea for keeping it consistent with our other repos!
